name: ga-tutorial
on: [push] 

jobs: 
  build:
    name: github action tutorial
    runs-on: ubuntu-18.04
    steps:
      - name: checkout
        uses: actions/checkout@master

      - name: print logs
        run: echo "presteps for build"
      
      - name: dependencies
        run: npm install 

      - name: build
        run: npm run build
